import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const service = readFileSync(join(process.cwd(), 'electron/services/aiAssistantService.ts'), 'utf8')
const store = readFileSync(join(process.cwd(), 'electron/services/personalMemoryStore.ts'), 'utf8')
const pageSource = readFileSync(join(process.cwd(), 'src/pages/AiAssistantPage.tsx'), 'utf8')
const pageStart = service.indexOf('  async searchMemoryPage(')
const pageEnd = service.indexOf('\n  getMemoryEvidencePage(', pageStart)
const page = service.slice(pageStart, pageEnd)
const questionStart = service.indexOf('  private async runMemoryQuestion(')
const questionEnd = service.indexOf('\n  private ', questionStart + 10)
const question = service.slice(questionStart, questionEnd)

test('memory search facets stay in SQLCipher instead of materializing one id set per facet', () => {
  assert.ok(pageStart > 0 && pageEnd > pageStart)
  assert.equal((page.match(/listScopedSearchDocumentIds\(/g) || []).length, 0)
  assert.equal((page.match(/createSearchDocumentScope\(/g) || []).length, 1)
  assert.equal((page.match(/releaseSearchDocumentScope\(/g) || []).length, 1)
  assert.ok((page.match(/countSearchDocumentsInScope\(/g) || []).length >= 4)
  assert.doesNotMatch(page, /facetAllowedIds|trustFacetAllowedIds|supportFacetAllowedIds|conflictFacetAllowedIds/)
})

test('hybrid paging reuses the already authorized primary scope', () => {
  assert.match(page, /searchMemoryHybrid\([\s\S]*?\{ allowedIds \}\s*\)/)
})

test('evidence Q&A reuses one SQLCipher scope across planning branches and releases it before model I/O', () => {
  assert.ok(questionStart > 0 && questionEnd > questionStart)
  assert.equal((question.match(/listScopedSearchDocumentIds\(/g) || []).length, 0)
  assert.equal((question.match(/createSearchDocumentScope\(/g) || []).length, 1)
  assert.equal((question.match(/releaseSearchDocumentScope\(/g) || []).length, 1)
  assert.ok((question.match(/\{ allowedIds: plannedScope \}/g) || []).length >= 2)
  assert.match(question, /findGraphPath\([\s\S]*?plannedScope/)
  assert.match(service, /const authorityPath = personalMemoryStore\.findRelationPath\([\s\S]*?relationScope/)
  assert.doesNotMatch(service.slice(service.indexOf('  findGraphPath('), questionStart), /findScopedGraphPath|new Map<string, Array/)
  assert.match(store, /findRelationPath\([\s\S]*?SearchDocumentScopeHandle \| null[\s\S]*?WITH RECURSIVE eligible_edges/)
  assert.match(store, /SCOPED_GRAPH_PATH_EXPANSION_LIMIT = 50_000[\s\S]*?ORDER BY 2 ASC,1 ASC[\s\S]*?LIMIT \?/)
  assert.match(question, /达到安全预算，当前不能证明范围内不存在连接/)
  assert.doesNotMatch(question, /new Set\(scopedRelationIds\)|listSearchDocumentSourceIdsInScope/)
  assert.ok(
    question.indexOf('releaseSearchDocumentScope(plannedScope)')
      < question.indexOf('runWithMemoryScopeRevalidation(')
  )
})

test('scope planning is honest and visible in complete diagnostics', () => {
  assert.match(store, /memorySearchScopePlanning:\s*\{[\s\S]*?version: 14[\s\S]*?facetStrategy: 'sqlcipher_direct_count'[\s\S]*?facetIdentityMaterializations: 0[\s\S]*?primaryScopeStrategy: 'sqlcipher_isolated_temp_table'[\s\S]*?primaryIdentityMaterializations: 0[\s\S]*?hybridScopeReused: true[\s\S]*?releasedAfterRequest: true[\s\S]*?handleOnlyScopeApi: true[\s\S]*?legacySharedScopeRemoved: true[\s\S]*?scopedGraphPathStrategy: 'sqlcipher_recursive_cte'[\s\S]*?scopedGraphRelationIdentityMaterializations: 0[\s\S]*?scopedGraphPathExpansionBudget: SCOPED_GRAPH_PATH_EXPANSION_LIMIT[\s\S]*?scopedGraphPathBreadthFirst: true[\s\S]*?scopedGraphPathTruncationVisible: true[\s\S]*?unscopedGraphPathStrategy: 'sqlcipher_recursive_cte'[\s\S]*?unscopedGraphAdjacencyMaterializations: 0[\s\S]*?commonNeighborStrategy: 'sqlcipher_ranked_aggregate'[\s\S]*?commonNeighborLimit: COMMON_GRAPH_NEIGHBOR_LIMIT[\s\S]*?commonNeighborEdgeLimitPerSide: COMMON_GRAPH_EDGE_LIMIT_PER_SIDE[\s\S]*?commonNeighborTotalVisible: true[\s\S]*?commonNeighborPagination: true[\s\S]*?commonNeighborRevisionBound: true[\s\S]*?commonNeighborContinuationRecoverable: true[\s\S]*?graphViewportStrategy: 'sqlcipher_recursive_cte'[\s\S]*?graphViewportIdentityMaterializations: 0[\s\S]*?graphViewportRelationLimit: GRAPH_VIEWPORT_RELATION_LIMIT[\s\S]*?graphViewportTruncationVisible: true[\s\S]*?graphFocusStrategy: 'sqlcipher_ranked_preview'[\s\S]*?graphFocusRelationLimit: 200[\s\S]*?graphFocusInsightAuthority: 'sqlcipher_counts'[\s\S]*?graphFocusEntityNameHydration: 'requested_only'[\s\S]*?entityTaskStrategy: 'sqlcipher_name_evidence_page'[\s\S]*?entityTaskIdentityMaterializations: 0[\s\S]*?entityTaskEvidenceLimit: MEMORY_CARD_EVIDENCE_LIMIT[\s\S]*?entityTaskRevisionBound: true[\s\S]*?trustedEntityDirectoryStrategy: 'sqlcipher_ranked_page'[\s\S]*?trustedEntityDirectoryIdentityMaterializations: 0[\s\S]*?trustedEntityDirectoryCollisionAuthority: 'sqlcipher_full_trusted_scope'[\s\S]*?trustedEntityDirectoryRevisionBound: true[\s\S]*?trustedEntityPresentationHydration: 'requested_ids_only'[\s\S]*?extractionContextStrategy: 'sqlcipher_ranked_direct_plus_one_hop'[\s\S]*?extractionContextEntityLimit: 24[\s\S]*?extractionContextRelationLimit: 40[\s\S]*?extractionContextAliasesPerEntity: 8[\s\S]*?extractionContextRevisionBound: true[\s\S]*?extractionContextFullGraphMaterializations: 0[\s\S]*?questionEntityPlanningStrategy: 'sqlcipher_reverse_term_match'[\s\S]*?questionEntityPlanningLimit: 100[\s\S]*?questionEntityPlanningTotalVisible: true[\s\S]*?questionEntityPlanningTruncationSafe: true/)
  assert.doesNotMatch(store, /replaceActiveSearchScope|CREATE TEMP TABLE IF NOT EXISTS active_memory_search_scope\s*\(/)
  assert.doesNotMatch(store, /type SearchDocumentScope\s*=\s*Set/)
  assert.match(pageSource, /检索范围执行策略[\s\S]*?SQLCipher 直接计数[\s\S]*?主检索范围 <b>SQLCipher 临时范围[\s\S]*?旧共享范围[\s\S]*?已移除[\s\S]*?范围内图路径[\s\S]*?SQLCipher 最短路径[\s\S]*?关系 ID 集合[\s\S]*?图路径扩展预算[\s\S]*?预算截断[\s\S]*?明确提示/)
  assert.match(pageSource, /当前不能证明 6 层内不存在连接[\s\S]*?缩小图谱或检索范围后重试/)
  assert.match(pageSource, /共同实体 <b>[\s\S]*?SQLCipher 聚合[\s\S]*?共同实体预算/)
  assert.match(pageSource, /当前按关系强度展示前[\s\S]*?完整总数来自 SQLCipher/)
  assert.match(pageSource, /loadMoreGraphCommonNeighbors[\s\S]*?expectedGraphRevision: graphCommonNeighbors\.graphRevision/)
  assert.match(pageSource, /graphPairQueryGate\.current\.begin\(\)[\s\S]*?graphPairQueryGate\.current\.isCurrent/)
  assert.match(pageSource, /加载更多（已加载[\s\S]*?graphCommonNeighbors\.total/)
  assert.match(pageSource, /图谱视口 <b>[\s\S]*?SQLCipher 多跳扩展[\s\S]*?画布关系预算/)
  assert.match(pageSource, /人物聚焦关系 <b>[\s\S]*?SQLCipher 有界预览[\s\S]*?关系强度统计[\s\S]*?权威计数/)
  assert.match(pageSource, /人物关联事项 <b>[\s\S]*?SQLCipher 完整分页[\s\S]*?任务原文预览/)
  assert.match(pageSource, /可信实体目录 <b>[\s\S]*?SQLCipher 搜索分页[\s\S]*?实体目录 ID 集合[\s\S]*?同名碰撞[\s\S]*?全可信范围计数[\s\S]*?实体选择[\s\S]*?revision 保护[\s\S]*?实体展示水合[\s\S]*?仅查询所需 ID/)
  assert.match(pageSource, /抽取上下文[\s\S]*?SQLCipher 直接命中＋一跳[\s\S]*?抽取实体预算[\s\S]*?extractionContextEntityLimit[\s\S]*?抽取关系预算[\s\S]*?extractionContextRelationLimit[\s\S]*?全图内存副本[\s\S]*?extractionContextFullGraphMaterializations[\s\S]*?抽取上下文一致性[\s\S]*?实体＋关系 revision 保护/)
  assert.match(pageSource, /问答实体识别[\s\S]*?SQLCipher 反向词匹配[\s\S]*?单轮规划预算[\s\S]*?questionEntityPlanningLimit[\s\S]*?超预算语义[\s\S]*?显示总数且禁止单人自动绑定/)
  assert.match(pageSource, /稠密关系已按 SQLCipher 安全预算隐藏/)
})

test('graph viewport selection and relation budgets stay in SQLCipher', () => {
  const start = service.indexOf('  getGraphWorkspace(')
  const end = service.indexOf('\n  getTrustedEntityDirectory(', start)
  const workspace = service.slice(start, end)
  assert.ok(start > 0 && end > start)
  assert.match(workspace, /personalMemoryStore\.buildGraphViewport\(/)
  assert.match(workspace, /selection: 'sqlcipher_recursive_cte'/)
  assert.doesNotMatch(workspace, /buildGraphViewport\(this\.state\.graph/)
  assert.doesNotMatch(workspace, /summary:\s*\{[\s\S]*?this\.state\.graph\.relations\.filter/)
  assert.match(store, /buildGraphViewport\([\s\S]*?WITH RECURSIVE[\s\S]*?GRAPH_VIEWPORT_RELATION_LIMIT/)
  const viewportStore = store.slice(store.indexOf('  buildGraphViewport('),
    store.indexOf('\n  findCommonRelationNeighbors(', store.indexOf('  buildGraphViewport(')))
  assert.match(viewportStore, /eligible_edges\(from_id,to_id\)/)
  assert.match(viewportStore, /degree_rows\(id\)/)
  assert.doesNotMatch(viewportStore, /relation\.subject_id=walk\.id OR relation\.object_id=walk\.id/)
  assert.match(workspace, /getEntityGraphFocus\(focusEntity\.id, 200\)/)
  assert.match(workspace, /authoritativeRelationships/)
  assert.match(workspace, /getEntityCanonicalNames\(\[\.\.\.namedEntityIds\]\)/)
  assert.doesNotMatch(workspace, /const allRelations = this\.state\.graph\.relations/)
  assert.match(workspace, /listEntityRelatedTaskPage\([\s\S]*?entityTaskSearchNames/)
  assert.doesNotMatch(workspace, /paginateEntityRelatedTasks|filter\(task => task\.classification === 'mine'\)/)
  const taskPageStart = service.indexOf('  getEntityTaskPage(')
  const taskPageEnd = service.indexOf('\n  getEntityAuditPage(', taskPageStart)
  const taskPage = service.slice(taskPageStart, taskPageEnd)
  assert.match(taskPage, /listEntityRelatedTaskPage\(/)
  assert.doesNotMatch(taskPage, /paginateEntityRelatedTasks|taskRelatesToEntity/)
  assert.match(store, /listEntityRelatedTaskPage\([\s\S]*?task\.classification='mine'[\s\S]*?search_document_evidence[\s\S]*?ROW_NUMBER\(\) OVER \(PARTITION BY document_id/)
  assert.match(store, /nextOffset: offset \+ rows\.length/)
  assert.match(pageSource, /offset: Number\(focus\.taskOffset \|\| focus\.tasks\?\.length \|\| 0\)/)
  assert.match(pageSource, /taskOffset: page\.nextOffset/)
})
